# Generated by Django 6.0.1 on 2026-02-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userkyc',
            name='business_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userkyc',
            name='business_registration_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='userkyc',
            name='contact_person_details',
            field=models.TextField(),
        ),
    ]
