# Generated by Django 5.2.10 on 2026-01-20 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
