# Generated by Django 6.0.1 on 2026-02-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0007_webhooksecret'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined']},
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['code'], name='users_otp_code_2787b0_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['is_used'], name='users_otp_is_used_14721c_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['user'], name='users_otp_user_id_525613_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_user_email_6f2530_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='users_user_usernam_65d164_idx'),
        ),
        migrations.AddIndex(
            model_name='userkyc',
            index=models.Index(fields=['users'], name='users_userk_users_i_e72b31_idx'),
        ),
        migrations.AddIndex(
            model_name='userkyc',
            index=models.Index(fields=['approved'], name='users_userk_approve_269122_idx'),
        ),
        migrations.AddIndex(
            model_name='webhooksecret',
            index=models.Index(fields=['user'], name='users_webho_user_id_9b7da1_idx'),
        ),
        migrations.AddIndex(
            model_name='webhooksecret',
            index=models.Index(fields=['is_active'], name='users_webho_is_acti_816ab6_idx'),
        ),
    ]
