# Generated by Django 6.0.1 on 2026-02-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_options_user_is_verified_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userkyc',
            name='users_userk_users_i_e72b31_idx',
        ),
        migrations.RenameField(
            model_name='userkyc',
            old_name='users',
            new_name='user',
        ),
        migrations.AddIndex(
            model_name='userkyc',
            index=models.Index(fields=['user'], name='users_userk_user_id_681a1c_idx'),
        ),
    ]
