# Generated by Django 6.0.1 on 2026-02-03 19:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCustomerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('item_summary', models.TextField()),
                ('tracking_status', models.CharField(choices=[('PENDING', 'Pending'), ('IN TRANSIT', 'In transit'), ('OUT FOR DELIVERY', 'Our for delivery'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=20)),
                ('customer_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderReceptions.ordercustomerdetails')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN TRANSIT', 'In transit'), ('OUT FOR DELIVERY', 'Our for delivery'), ('DELIVERED', 'Delivered')], max_length=25)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderReceptions.orderdetails')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
