# Generated by Django 6.0.1 on 2026-02-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderReceptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatushistory',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
