# Generated by Django 6.0.1 on 2026-01-23 12:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderReceptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN TRANSIT', 'In transit'), ('OUT FOR DELIVERY', 'Our for delivery'), ('DELIVERED', 'Delivered')], max_length=25)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderReceptions.orderdetails')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
